<?php
/**
 * The dynamic Spotlight Posts block.
 *
 * @package Spotlight_Posts
 */

declare( strict_types = 1 );

namespace Spotlight_Posts\Frontend;

use Spotlight_Posts\Featured\FeaturedPost;
use Spotlight_Posts\Featured\Repository;
use Spotlight_Posts\Registrable;

defined( 'ABSPATH' ) || exit;

/**
 * Registers and server-renders the featured list block.
 *
 * Rendered on the server so the markup always reflects current cache state rather than
 * whatever was serialized into post content at save time.
 */
final class Block implements Registrable {

	/**
	 * Directory holding the compiled block metadata, relative to the plugin root.
	 */
	private const BUILD_PATH = 'build/featured-list';

	/**
	 * Source of the spotlighted posts.
	 *
	 * @var Repository
	 */
	private Repository $repository;

	/**
	 * Absolute path to the plugin directory.
	 *
	 * @var string
	 */
	private string $plugin_dir;

	/**
	 * @param Repository $repository Source of the spotlighted posts.
	 * @param string     $plugin_dir Absolute path to the plugin directory.
	 */
	public function __construct( Repository $repository, string $plugin_dir ) {
		$this->repository = $repository;
		$this->plugin_dir = rtrim( $plugin_dir, '/' ) . '/';
	}

	/**
	 * Register the block on init.
	 */
	public function register(): void {
		add_action( 'init', array( $this, 'register_block' ) );
	}

	/**
	 * Register the block from its compiled metadata.
	 *
	 * No-ops when build/ is absent, which keeps a freshly cloned checkout from fataling
	 * before `npm run build` has run.
	 */
	public function register_block(): void {
		$path = $this->plugin_dir . self::BUILD_PATH;

		if ( ! file_exists( $path . '/block.json' ) ) {
			return;
		}

		$block_type = register_block_type(
			$path,
			array(
				'render_callback' => array( $this, 'render' ),
			)
		);

		/*
		 * The editor script handle is generated by core from the block name, so it is read
		 * back off the registered type rather than hardcoded -- a hardcoded guess breaks
		 * silently if the block is renamed, losing translations with no error.
		 */
		if ( $block_type instanceof \WP_Block_Type && ! empty( $block_type->editor_script_handles ) ) {
			foreach ( $block_type->editor_script_handles as $handle ) {
				wp_set_script_translations( $handle, 'spotlight-posts' );
			}
		}
	}

	/**
	 * Render the list.
	 *
	 * Every dynamic value is escaped at the point of output with the escaper that matches
	 * its context: esc_url() for hrefs, esc_html() for text nodes.
	 *
	 * @param array<string, mixed> $attributes Block attributes.
	 * @return string Rendered HTML.
	 */
	public function render( array $attributes ): string {
		$heading = isset( $attributes['heading'] ) ? (string) $attributes['heading'] : '';

		/*
		 * The heading level is configurable because a fixed h2 breaks the document outline
		 * wherever the block is not actually the second level on the page -- which screen
		 * reader users navigate by. Clamped to h2-h6: h1 belongs to the page title, and
		 * anything outside the range is not a heading at all.
		 */
		$level       = isset( $attributes['headingLevel'] ) ? (int) $attributes['headingLevel'] : 2;
		$heading_tag = 'h' . max( 2, min( 6, $level ) );

		$count = isset( $attributes['numberOfPosts'] ) ? (int) $attributes['numberOfPosts'] : 5;
		$fill  = ! empty( $attributes['fillWithRecent'] );
		$posts = $this->repository->find( $count, $fill );

		ob_start();
		?>
		<div <?php echo wp_kses_data( get_block_wrapper_attributes() ); ?>>
			<?php if ( '' !== $heading ) : ?>
				<<?php echo esc_html( $heading_tag ); ?> class="wp-block-spotlight-posts-featured-list__heading">
					<?php echo esc_html( $heading ); ?>
				</<?php echo esc_html( $heading_tag ); ?>>
			<?php endif; ?>

			<?php if ( empty( $posts ) ) : ?>
				<p class="wp-block-spotlight-posts-featured-list__empty">
					<?php esc_html_e( 'No featured posts yet.', 'spotlight-posts' ); ?>
				</p>
			<?php else : ?>
				<ul class="wp-block-spotlight-posts-featured-list__list">
					<?php foreach ( $posts as $post ) : ?>
						<?php if ( ! $post instanceof FeaturedPost ) : ?>
							<?php continue; ?>
						<?php endif; ?>
						<li class="wp-block-spotlight-posts-featured-list__item">
							<a href="<?php echo esc_url( $post->url ); ?>">
								<?php echo esc_html( $post->title ); ?>
							</a>
							<?php if ( '' !== $post->excerpt ) : ?>
								<p class="wp-block-spotlight-posts-featured-list__excerpt">
									<?php echo esc_html( $post->excerpt ); ?>
								</p>
							<?php endif; ?>
						</li>
					<?php endforeach; ?>
				</ul>
			<?php endif; ?>
		</div>
		<?php

		return (string) ob_get_clean();
	}
}
